# This file is a part of configuration , default setup enable sqlite module 
#and need sqlite3 as depencies for work.

enabled = true
debug = true
adapter = "sqlite"
[dependencies]
module="sqlite3"

#Watch Exchange Market : default setup BTC-LTC

#Bitfinex - Kraken - Poloniex - Exmo
#api keys can be obtained after registration and identity verification
[watch]
exchange = "bitfinex"
currency = "BTC"
asset = "LTC"
key=""
secret=""
[watch]
exchange = "kraken"
currency = "XBT"
asset = "LTC"
key=""
secret=""
[watch]
exchange = "poloniex"
currency = "BTC"
asset = "LTC"
key=""
secret=""
[watch]
exchange = "exmo"
currency = "BTC"
asset = "LTC"
key=""
secret=""